// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package database

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (category, friendly_name, host_name, ip_address, description)
VALUES (?, ?, ?, ?, ?)
RETURNING id, category, friendly_name, host_name, ip_address, description
`

type CreateEntryParams struct {
	Category     int64
	FriendlyName string
	HostName     string
	IpAddress    string
	Description  string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Category,
		arg.FriendlyName,
		arg.HostName,
		arg.IpAddress,
		arg.Description,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.FriendlyName,
		&i.HostName,
		&i.IpAddress,
		&i.Description,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const editEntryByID = `-- name: EditEntryByID :one
UPDATE entries
SET
    category = ?,
    friendly_name = ?,
    host_name = ?,
    ip_address = ?,
    description = ?
WHERE id = ?
RETURNING id, category, friendly_name, host_name, ip_address, description
`

type EditEntryByIDParams struct {
	Category     int64
	FriendlyName string
	HostName     string
	IpAddress    string
	Description  string
	ID           int64
}

func (q *Queries) EditEntryByID(ctx context.Context, arg EditEntryByIDParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, editEntryByID,
		arg.Category,
		arg.FriendlyName,
		arg.HostName,
		arg.IpAddress,
		arg.Description,
		arg.ID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.FriendlyName,
		&i.HostName,
		&i.IpAddress,
		&i.Description,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT id, category, friendly_name, host_name, ip_address, description FROM entries
ORDER BY id ASC
`

func (q *Queries) GetEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.FriendlyName,
			&i.HostName,
			&i.IpAddress,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByCategory = `-- name: GetEntriesByCategory :many
SELECT id, category, friendly_name, host_name, ip_address, description FROM entries
WHERE category = ?
`

func (q *Queries) GetEntriesByCategory(ctx context.Context, category int64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.FriendlyName,
			&i.HostName,
			&i.IpAddress,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, category, friendly_name, host_name, ip_address, description FROM entries
WHERE ID = ?
`

func (q *Queries) GetEntryByID(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.FriendlyName,
		&i.HostName,
		&i.IpAddress,
		&i.Description,
	)
	return i, err
}
