// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Entry struct {
	ID           int64
	Category     int64
	FriendlyName string
	HostName     string
	IpAddress    string
	Description  string
}
